#!/bin/bash

export OMP_NUM_THREADS=1
export GLOO_SOCKET_IFNAME=ib0
export NCCL_IB_DISABLE=1
export NCCL_SOCKET_IFNAME=ib0
export NCCL_IB_HCA=$(pushd /sys/class/infiniband/ > /dev/null; for i in mlx5_*; do cat $i/ports/1/gid_attrs/types/* 2>/dev/null | grep v >/dev/null && echo $i ; done; popd > /dev/null)
export NCCL_TREE_THRESHOLD=0

python3 /home/huangricong/Data/packnet_discriminator/packnet_sfm/networks/depth/FPTResNet/tools/test_net.py $@